server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: course
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
    jmx:
      enabled: false
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: >
      jdbc:mariadb://127.0.0.1:3306/devdojo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&
      useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root
