version: '3.8'
services:
  db:
    image: mariadb
    container_name: mariadb_devdojo
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - microservices_devdojo:/var/lib/mysql

volumes:
  microservices_devdojo:
